# Generated by Django 5.2.14 on 2026-06-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_client_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issue_date', '-id'], 'verbose_name': 'Fatura', 'verbose_name_plural': 'Faturas'},
        ),
    ]
